import { Santri, TahfidzProgress, SppBill, SpmbRegistrant } from './types';

export const DEFAULT_SANTRI: Santri[] = [
  {
    id: 's1',
    name: 'Ahmad Faiz Al-Fatih',
    class: 'Kelas IX-A',
    parentName: 'Rahmat Sulaiman',
    nis: '20260101',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
  },
  {
    id: 's2',
    name: 'M. Wildan Al-Ghazali',
    class: 'Kelas IX-A',
    parentName: 'Hendy Hermawan',
    nis: '20260102',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  {
    id: 's3',
    name: 'Fatimah Az-Zahra',
    class: 'Kelas VIII-B',
    parentName: 'Faisal Basri',
    nis: '20260201',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  },
  {
    id: 's4',
    name: 'Yusuf Nur Rahman',
    class: 'Kelas VII-C',
    parentName: 'Ahmad Muzadi',
    nis: '20260305',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  },
  {
    id: 's5',
    name: 'Aisyah Humaira',
    class: 'Kelas VII-B',
    parentName: 'Lukman Hakim',
    nis: '20260312',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
  },
];

export const DEFAULT_TAHFIDZ: TahfidzProgress[] = [
  {
    id: 't1',
    santriId: 's1',
    surahName: 'An-Naba',
    startAyat: 1,
    endAyat: 40,
    juz: 30,
    tajwidScore: 92,
    fluentScore: 95,
    notes: 'Sangat lancar, makharijul huruf tepat. Pertahankan!',
    date: '2026-06-28',
    ustadzName: 'Ustadz Hamzah Al-Hafidz',
  },
  {
    id: 't2',
    santriId: 's1',
    surahName: 'An-Naziat',
    startAyat: 1,
    endAyat: 20,
    juz: 30,
    tajwidScore: 88,
    fluentScore: 90,
    notes: 'Perhatikan dengung pada ayat 15.',
    date: '2026-07-02',
    ustadzName: 'Ustadz Hamzah Al-Hafidz',
  },
  {
    id: 't3',
    santriId: 's2',
    surahName: 'Al-Mulk',
    startAyat: 1,
    endAyat: 15,
    juz: 29,
    tajwidScore: 85,
    fluentScore: 80,
    notes: 'Ulangi lagi di rumah, kelancaran masih perlu ditingkatkan.',
    date: '2026-06-29',
    ustadzName: 'Ustadz Mansur',
  },
  {
    id: 't4',
    santriId: 's2',
    surahName: 'Al-Mulk',
    startAyat: 16,
    endAyat: 30,
    juz: 29,
    tajwidScore: 90,
    fluentScore: 88,
    notes: 'Perkembangan bagus, tajwid mad thabi’i sudah konsisten.',
    date: '2026-07-03',
    ustadzName: 'Ustadz Mansur',
  },
  {
    id: 't5',
    santriId: 's3',
    surahName: 'Yasin',
    startAyat: 1,
    endAyat: 40,
    juz: 22,
    tajwidScore: 95,
    fluentScore: 96,
    notes: 'MasyaAllah, bacaan sangat tartil dan tajwid sempurna.',
    date: '2026-07-01',
    ustadzName: 'Ustadz Abdul Malik',
  },
  {
    id: 't6',
    santriId: 's4',
    surahName: 'Al-Baqarah',
    startAyat: 1,
    endAyat: 24,
    juz: 1,
    tajwidScore: 82,
    fluentScore: 80,
    notes: 'Hati-hati tertukar harakat panjang pendek di ayat-ayat awal.',
    date: '2026-07-03',
    ustadzName: 'Ustadz Hamzah Al-Hafidz',
  },
  {
    id: 't7',
    santriId: 's5',
    surahName: 'Al-Insan',
    startAyat: 1,
    endAyat: 31,
    juz: 29,
    tajwidScore: 94,
    fluentScore: 92,
    notes: 'Hafalan kokoh dan lancar sekali.',
    date: '2026-07-02',
    ustadzName: 'Ustadz Abdul Malik',
  },
];

export const DEFAULT_SPP_BILLS: SppBill[] = [
  // Ahmad Faiz Al-Fatih (s1)
  {
    id: 'b1',
    santriId: 's1',
    category: 'SPP Bulanan',
    month: 'Juli',
    year: 2026,
    amount: 1200000,
    status: 'Lunas',
    dueDate: '2026-07-10',
  },
  {
    id: 'b2',
    santriId: 's1',
    category: 'Uang Makan',
    month: 'Juli',
    year: 2026,
    amount: 600000,
    status: 'Lunas',
    dueDate: '2026-07-10',
  },
  {
    id: 'b3',
    santriId: 's1',
    category: 'Uang Gedung',
    month: 'Juli',
    year: 2026,
    amount: 1500000,
    status: 'Pending',
    dueDate: '2026-07-15',
  },

  // M. Wildan Al-Ghazali (s2)
  {
    id: 'b4',
    santriId: 's2',
    category: 'SPP Bulanan',
    month: 'Juli',
    year: 2026,
    amount: 1200000,
    status: 'Pending',
    dueDate: '2026-07-10',
  },
  {
    id: 'b5',
    santriId: 's2',
    category: 'Uang Makan',
    month: 'Juli',
    year: 2026,
    amount: 600000,
    status: 'Pending',
    dueDate: '2026-07-10',
  },

  // Fatimah Az-Zahra (s3)
  {
    id: 'b6',
    santriId: 's3',
    category: 'SPP Bulanan',
    month: 'Juli',
    year: 2026,
    amount: 1200000,
    status: 'Lunas',
    dueDate: '2026-07-10',
  },
  {
    id: 'b7',
    santriId: 's3',
    category: 'Uang Makan',
    month: 'Juli',
    year: 2026,
    amount: 600000,
    status: 'Lunas',
    dueDate: '2026-07-10',
  },
];

export const DEFAULT_SPMB_REGISTRANTS: SpmbRegistrant[] = [
  {
    id: 'reg1',
    name: 'Rayhan Ghazi Pratama',
    gender: 'Laki-laki',
    schoolOrigin: 'SDN 01 Menteng Jakarta',
    registrationDate: '2026-06-15',
    examScore: 88,
    documentStatus: 'Lengkap',
    status: 'Lulus',
    parentPhone: '081234567890',
  },
  {
    id: 'reg2',
    name: 'Nabila Shafa Kamila',
    gender: 'Perempuan',
    schoolOrigin: 'SD Islam Al-Azhar Surabaya',
    registrationDate: '2026-06-18',
    examScore: 92,
    documentStatus: 'Lengkap',
    status: 'Lulus',
    parentPhone: '081223344556',
  },
  {
    id: 'reg3',
    name: 'Zaki Mubarak Al-Husaini',
    gender: 'Laki-laki',
    schoolOrigin: 'MIN 2 Yogyakarta',
    registrationDate: '2026-06-22',
    examScore: 78,
    documentStatus: 'Belum Lengkap',
    status: 'Pending',
    parentPhone: '085711223344',
  },
  {
    id: 'reg4',
    name: 'Humaira Husna',
    gender: 'Perempuan',
    schoolOrigin: 'SDIT Luqman Al-Hakim Bandung',
    registrationDate: '2026-06-25',
    examScore: 84,
    documentStatus: 'Lengkap',
    status: 'Pending',
    parentPhone: '089876543210',
  },
  {
    id: 'reg5',
    name: 'Fadhil Ihsan',
    gender: 'Laki-laki',
    schoolOrigin: 'SDN 4 Solo',
    registrationDate: '2026-06-30',
    examScore: 60,
    documentStatus: 'Lengkap',
    status: 'Gagal',
    parentPhone: '081344556677',
  },
];
